// AUTO-GENERATED by gen-config.mjs. Do not hand-edit -- regenerate instead.
import { defineConfig, markdown } from "sourcey";

export default defineConfig({
  name: "OpenSearch Observability Stack",
  siteUrl: "https://observability.opensearch.org",
  baseUrl: "/docs",
  prettyUrls: "slash",
  repo: "https://github.com/opensearch-project/observability-stack",
  editBranch: "main",
  editBasePath: "docs/starlight-docs/src/content/docs",
  navigation: {
    tabs: [
      {
        tab: "Overview",
        slug: "",
        source: markdown({
          groups: [{ group: "overview", pages: ["index"] }],
        }),
      },
      {
        tab: "Agent Health",
        slug: "agent-health",
        source: markdown({
          groups: [{ group: "agent-health", pages: ["agent-health","agent-health/cli","agent-health/configuration","agent-health/configuration/connectors","agent-health/evaluations","agent-health/evaluations/experiments","agent-health/evaluations/test-cases","agent-health/getting-started","agent-health/traces"] }],
        }),
      },
      {
        tab: "AI Observability",
        slug: "ai-observability",
        source: markdown({
          groups: [{ group: "ai-observability", pages: ["ai-observability","ai-observability/agent-tracing","ai-observability/agent-tracing/graph","ai-observability/evaluation","ai-observability/evaluation-integrations","ai-observability/getting-started"] }],
        }),
      },
      {
        tab: "Alerting",
        slug: "alerting",
        source: markdown({
          groups: [{ group: "alerting", pages: ["alerting","alerting/unified-alerts"] }],
        }),
      },
      {
        tab: "Anomaly Detection",
        slug: "anomaly-detection",
        source: markdown({
          groups: [{ group: "anomaly-detection", pages: ["anomaly-detection"] }],
        }),
      },
      {
        tab: "Application Monitoring",
        slug: "apm",
        source: markdown({
          groups: [{ group: "apm", pages: ["apm","apm/configuring-apm","apm/configuring-telemetry-ingestion","apm/service-map","apm/services","apm/sizing-calculator"] }],
        }),
      },
      {
        tab: "Claude Code",
        slug: "claude-code",
        source: markdown({
          groups: [{ group: "claude-code", pages: ["claude-code","claude-code/showcase","claude-code/usage"] }],
        }),
      },
      {
        tab: "Dashboards & Visualize",
        slug: "dashboards",
        source: markdown({
          groups: [{ group: "dashboards", pages: ["dashboards","dashboards/build","dashboards/sharing","dashboards/troubleshooting","dashboards/variables","dashboards/variables/managing-variables","dashboards/variables/using-variables","dashboards/visualize","dashboards/visualize/area-chart","dashboards/visualize/bar-chart","dashboards/visualize/bar-gauge-chart","dashboards/visualize/configuring-visualizations","dashboards/visualize/configuring-visualizations/thresholds","dashboards/visualize/configuring-visualizations/value-calculations","dashboards/visualize/gauge-chart","dashboards/visualize/heatmap-chart","dashboards/visualize/histogram-chart","dashboards/visualize/line-chart","dashboards/visualize/metric-chart","dashboards/visualize/pie-chart","dashboards/visualize/scatter-chart","dashboards/visualize/state-timeline-chart","dashboards/visualize/table-chart","dashboards/visualize/transformations"] }],
        }),
      },
      {
        tab: "Deploy to Cloud",
        slug: "deploy",
        source: markdown({
          groups: [{ group: "deploy", pages: ["deploy","deploy/aws","deploy/kubernetes"] }],
        }),
      },
      {
        tab: "Forecasting",
        slug: "forecasting",
        source: markdown({
          groups: [{ group: "forecasting", pages: ["forecasting"] }],
        }),
      },
      {
        tab: "Get Started",
        slug: "get-started",
        source: markdown({
          groups: [{ group: "get-started", pages: ["get-started/core-concepts","get-started/installation","get-started/overview","get-started/quickstart/first-dashboard","get-started/quickstart/first-traces"] }],
        }),
      },
      {
        tab: "Discover",
        slug: "investigate",
        source: markdown({
          groups: [{ group: "investigate", pages: ["investigate","investigate/correlations","investigate/datasets","investigate/discover-logs","investigate/discover-metrics","investigate/discover-traces","investigate/explore-logs","investigate/troubleshooting"] }],
        }),
      },
      {
        tab: "MCP",
        slug: "mcp",
        source: markdown({
          groups: [{ group: "mcp", pages: ["mcp"] }],
        }),
      },
      {
        tab: "PPL - Query Language",
        slug: "ppl",
        source: markdown({
          groups: [{ group: "ppl", pages: ["ppl","ppl/commands","ppl/commands/dedup","ppl/commands/describe","ppl/commands/eval","ppl/commands/eventstats","ppl/commands/expand","ppl/commands/fields","ppl/commands/fillnull","ppl/commands/flatten","ppl/commands/grok","ppl/commands/head","ppl/commands/join","ppl/commands/lookup","ppl/commands/ml","ppl/commands/parse","ppl/commands/patterns","ppl/commands/rare","ppl/commands/rename","ppl/commands/rex","ppl/commands/search","ppl/commands/sort","ppl/commands/spath","ppl/commands/stats","ppl/commands/streamstats","ppl/commands/timechart","ppl/commands/top","ppl/commands/trendline","ppl/commands/where","ppl/dql-lucene-users","ppl/examples","ppl/functions","ppl/spl-users"] }],
        }),
      },
      {
        tab: "Send Data",
        slug: "send-data",
        source: markdown({
          groups: [{ group: "send-data", pages: ["send-data","send-data/ai-agents","send-data/ai-agents/integrations","send-data/ai-agents/python","send-data/ai-agents/typescript","send-data/applications","send-data/applications/browser","send-data/applications/dotnet","send-data/applications/go","send-data/applications/java","send-data/applications/nodejs","send-data/applications/python","send-data/applications/ruby","send-data/data-pipeline","send-data/data-pipeline/batching","send-data/data-pipeline/data-prepper","send-data/data-pipeline/ingest-api","send-data/from-vendor","send-data/from-vendor/datadog","send-data/from-vendor/jaeger","send-data/from-vendor/splunk","send-data/infrastructure","send-data/infrastructure/aws","send-data/infrastructure/docker","send-data/infrastructure/fluentd","send-data/infrastructure/kubernetes","send-data/infrastructure/logstash","send-data/infrastructure/prometheus","send-data/opentelemetry","send-data/opentelemetry/auto-instrumentation","send-data/opentelemetry/collector","send-data/opentelemetry/manual-instrumentation","send-data/opentelemetry/sampling"] }],
        }),
      },
      {
        tab: "SLO",
        slug: "slo",
        source: markdown({
          groups: [{ group: "slo", pages: ["slo","slo/create","slo/detail"] }],
        }),
      },
    ],
  },
});
