{{- if and .Values.alertmanager.enabled .Values.alertmanager.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "observability-stack.fullname" . }}-alertmanager-data
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.alertmanager.persistence.size }}
  {{- with .Values.alertmanager.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
