{{- if and .Values.cortex.enabled .Values.cortex.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "observability-stack.fullname" . }}-cortex-data
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: cortex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cortex.persistence.size }}
  {{- with .Values.cortex.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
