{{- if .Values.rbac.enabled }}
{{- $fullName := include "observability-stack.fullname" . }}
{{- if .Values.rbac.admin.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullName }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $fullName }}-admin
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ $fullName }}-admin
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.rbac.admin.clusterRole }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-admin-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ $fullName }}-admin
type: kubernetes.io/service-account-token
{{- end }}
{{- if .Values.rbac.readonly.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullName }}-readonly
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $fullName }}-readonly
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ $fullName }}-readonly
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.rbac.readonly.clusterRole }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-readonly-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ $fullName }}-readonly
type: kubernetes.io/service-account-token
{{- end }}
{{- end }}
